# Generated by Django 4.0.4 on 2022-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('code', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
    ]
