# Generated by Django 4.0.4 on 2022-06-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('binary_image', models.BinaryField(blank=True, null=True)),
                ('h', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('body', models.TextField(default='')),
                ('type', models.CharField(choices=[('T', 'Texto'), ('I', 'Imagen')], default='T', max_length=8)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='document.document')),
            ],
        ),
    ]
