# Generated by Django 4.0.4 on 2022-05-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1024)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to='classroom.classroom')),
            ],
        ),
    ]
