# Generated by Django 4.0.4 on 2022-06-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('token', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ttl', models.IntegerField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to='classroom.classroom')),
            ],
        ),
    ]
