#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := e_printed_exam

include $(IDF_PATH)/make/project.mk

#EXTRA_COMPONENT_DIRS := components